#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"

# command line colors
PURPLE='\033[0;35m'
NOCOLOR='\033[0m'

# 0. message
echo "${PURPLE}[Husky] pre-push${NOCOLOR}"

# 1. run prettier check & format
echo "${PURPLE}[Prettier]${NOCOLOR}"
yarn prettier-check;
yarn prettier

# 2. run type check
echo "${PURPLE}[Type Check]${NOCOLOR}"
yarn type-check;

# 3. run eslint check & format
echo "${PURPLE}[ESLint]${NOCOLOR}"
yarn eslint-check;

# 4. run test
echo "${PURPLE}[Jest]${NOCOLOR}"
yarn test;
